---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/admin/layers":
    get:
      summary: List of layers
      tags:
      - Layer
      security:
      - tokenAuth: []
      parameters:
      - name: page
        in: query
        description: 'Page number. Default: 1'
        required: false
        schema:
          type: integer
      - name: per_page
        in: query
        description: 'Per page items. Default: 30'
        required: false
        schema:
          type: integer
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                success: false
                message: Invalid API Credentials
        '200':
          description: success
          content:
            application/json:
              example:
                success: true
                message: List of all Layers
                data:
                - name: molestiae
                  info: molestiae
                  legend:
                  title:
                  data_units:
                  processing:
                  description:
                  id: 9
                  layer_group_id:
                  slug: Layer-3
                  layer_type: molestiae
                  zindex: 25
                  active: false
                  order: 25
                  color: "#157e15"
                  layer_provider:
                  css:
                  interactivity: molestiae
                  opacity:
                  query:
                  created_at: '2023-03-15T13:03:56.376+01:00'
                  updated_at: '2023-03-15T13:03:56.376+01:00'
                  locate_layer: false
                  icon_class:
                  published: true
                  zoom_max: 100
                  zoom_min: 0
                  dashboard_order:
                  download: false
                  dataset_shortname:
                  dataset_source_url:
                  start_date:
                  end_date:
                  spatial_resolution:
                  spatial_resolution_units:
                  temporal_resolution:
                  temporal_resolution_units:
                  update_frequency:
                  version:
                  analysis_suitable: false
                  analysis_query:
                  layer_config:
                  analysis_body:
                  interaction_config:
                - name: cum
                  info: cum
                  legend:
                  title:
                  data_units:
                  processing:
                  description:
                  id: 8
                  layer_group_id:
                  slug: Layer-2
                  layer_type: cum
                  zindex: 41
                  active: true
                  order: 41
                  color: "#eaf1ea"
                  layer_provider:
                  css:
                  interactivity: cum
                  opacity:
                  query:
                  created_at: '2023-03-15T13:03:56.370+01:00'
                  updated_at: '2023-03-15T13:03:56.370+01:00'
                  locate_layer: false
                  icon_class:
                  published: true
                  zoom_max: 100
                  zoom_min: 0
                  dashboard_order:
                  download: false
                  dataset_shortname:
                  dataset_source_url:
                  start_date:
                  end_date:
                  spatial_resolution:
                  spatial_resolution_units:
                  temporal_resolution:
                  temporal_resolution_units:
                  update_frequency:
                  version:
                  analysis_suitable: false
                  analysis_query:
                  layer_config:
                  analysis_body:
                  interaction_config:
                - name: voluptatem
                  info: voluptatem
                  legend:
                  title:
                  data_units:
                  processing:
                  description:
                  id: 7
                  layer_group_id:
                  slug: Layer-1
                  layer_type: voluptatem
                  zindex: 38
                  active: true
                  order: 38
                  color: "#ffdbdb"
                  layer_provider:
                  css:
                  interactivity: voluptatem
                  opacity:
                  query:
                  created_at: '2023-03-15T13:03:56.364+01:00'
                  updated_at: '2023-03-15T13:03:56.364+01:00'
                  locate_layer: false
                  icon_class:
                  published: true
                  zoom_max: 100
                  zoom_min: 0
                  dashboard_order:
                  download: false
                  dataset_shortname:
                  dataset_source_url:
                  start_date:
                  end_date:
                  spatial_resolution:
                  spatial_resolution_units:
                  temporal_resolution:
                  temporal_resolution_units:
                  update_frequency:
                  version:
                  analysis_suitable: false
                  analysis_query:
                  layer_config:
                  analysis_body:
                  interaction_config:
                meta_attributes:
                  current_page: 1
                  next_page:
                  prev_page:
                  total_pages: 1
                  total_count: 3
    post:
      summary: Create new layer
      tags:
      - Layer
      security:
      - tokenAuth: []
      parameters: []
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                success: false
                message: Invalid API Credentials
        '200':
          description: success
          content:
            application/json:
              example:
                success: true
                message: Layer Created Successfully
                data:
                  name: voluptatem
                  info:
                  legend:
                  title:
                  data_units:
                  processing:
                  description:
                  id: 11
                  layer_group_id:
                  slug: Layer-1
                  layer_type: voluptatem
                  zindex: 38
                  active: true
                  order: 38
                  color: "#ffdbdb"
                  layer_provider:
                  css:
                  interactivity: voluptatem
                  opacity:
                  query:
                  created_at: '2023-03-15T13:03:56.436+01:00'
                  updated_at: '2023-03-15T13:03:56.436+01:00'
                  locate_layer: false
                  icon_class:
                  published: true
                  zoom_max: 100
                  zoom_min: 0
                  dashboard_order:
                  download: false
                  dataset_shortname:
                  dataset_source_url:
                  start_date:
                  end_date:
                  spatial_resolution:
                  spatial_resolution_units:
                  temporal_resolution:
                  temporal_resolution_units:
                  update_frequency:
                  version:
                  analysis_suitable: false
                  analysis_query:
                  layer_config:
                  analysis_body:
                  interaction_config:
        '422':
          description: Validation errors
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                layer:
                  type: object
  "/api/admin/layers/{id}":
    get:
      summary: Show detail of layer
      tags:
      - Layer
      security:
      - tokenAuth: []
      parameters:
      - name: id
        in: path
        description: Layer ID
        required: true
        schema:
          type: integer
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                success: false
                message: Invalid API Credentials
        '200':
          description: success
          content:
            application/json:
              example:
                success: true
                message: Layer Details
                data:
                  name: voluptatem
                  info: voluptatem
                  legend:
                  title:
                  data_units:
                  processing:
                  description:
                  id: 18
                  layer_group_id:
                  slug: Layer-1
                  layer_type: voluptatem
                  zindex: 38
                  active: true
                  order: 38
                  color: "#ffdbdb"
                  layer_provider:
                  css:
                  interactivity: voluptatem
                  opacity:
                  query:
                  created_at: '2023-03-15T13:03:56.546+01:00'
                  updated_at: '2023-03-15T13:03:56.546+01:00'
                  locate_layer: false
                  icon_class:
                  published: true
                  zoom_max: 100
                  zoom_min: 0
                  dashboard_order:
                  download: false
                  dataset_shortname:
                  dataset_source_url:
                  start_date:
                  end_date:
                  spatial_resolution:
                  spatial_resolution_units:
                  temporal_resolution:
                  temporal_resolution_units:
                  update_frequency:
                  version:
                  analysis_suitable: false
                  analysis_query:
                  layer_config:
                  analysis_body:
                  interaction_config:
        '422':
          description: Not Found
          content:
            application/json:
              example:
                success: false
                message: Layer not found
    delete:
      summary: Delete appropriate layer
      tags:
      - Layer
      security:
      - tokenAuth: []
      parameters:
      - name: id
        in: path
        description: Layer ID
        required: true
        schema:
          type: integer
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                success: false
                message: Invalid API Credentials
        '200':
          description: success
          content:
            application/json:
              example:
                success: true
                message: Layer Deleted Successfully
                data:
                  name:
                  info:
                  legend:
                  title:
                  data_units:
                  processing:
                  description:
                  id: 22
                  layer_group_id:
                  slug: Layer-1
                  layer_type: voluptatem
                  zindex: 38
                  active: true
                  order: 38
                  color: "#ffdbdb"
                  layer_provider:
                  css:
                  interactivity: voluptatem
                  opacity:
                  query:
                  created_at: '2023-03-15T13:03:56.694+01:00'
                  updated_at: '2023-03-15T13:03:56.694+01:00'
                  locate_layer: false
                  icon_class:
                  published: true
                  zoom_max: 100
                  zoom_min: 0
                  dashboard_order:
                  download: false
                  dataset_shortname:
                  dataset_source_url:
                  start_date:
                  end_date:
                  spatial_resolution:
                  spatial_resolution_units:
                  temporal_resolution:
                  temporal_resolution_units:
                  update_frequency:
                  version:
                  analysis_suitable: false
                  analysis_query:
                  layer_config:
                  analysis_body:
                  interaction_config:
        '422':
          description: Not Found
          content:
            application/json:
              example:
                success: false
                message: Errors
                error:
  "/users/authenticate":
    post:
      summary: Authenticate user (obtain token)
      tags:
      - User
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                auth_token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2Nzg5NjgyMzZ9.PqeseLiiDWiC6c8o2iULlM-fEZ2VcUmdonjNzaGnXwo
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                error:
                  user_authentication: invalid credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/categories":
    get:
      summary: Get list of categories
      tags:
      - Category
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                data:
                - id: '4'
                  type: categories
                  attributes:
                    name: voluptatem
                    slug: Category-1
                    description: Enim repellat pariatur. Earum modi eos. Libero tempora
                      exercitationem.
                  relationships:
                    indicators:
                      data: []
                - id: '5'
                  type: categories
                  attributes:
                    name: cum
                    slug: Category-2
                    description: Placeat commodi libero. Quo recusandae repellat.
                      Sunt commodi tempore.
                  relationships:
                    indicators:
                      data: []
                - id: '6'
                  type: categories
                  attributes:
                    name: molestiae
                    slug: Category-3
                    description: Et quaerat omnis. Harum voluptas atque. Quo nesciunt
                      voluptas.
                  relationships:
                    indicators:
                      data: []
                meta:
                  total_categories: 3
  "/api/indicators":
    get:
      summary: Get list of indicators
      tags:
      - Indicator
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                data:
                - id: '4'
                  type: indicators
                  attributes:
                    name: voluptatem
                    slug: Category-1
                    version: voluptatem
                    position: 38
                    column_name: voluptatem
                    operation: voluptatem
                  relationships:
                    models:
                      data: []
                    category:
                      data:
                        id: '10'
                        type: categories
                - id: '5'
                  type: indicators
                  attributes:
                    name: cum
                    slug: Category-2
                    version: cum
                    position: 41
                    column_name: cum
                    operation: cum
                  relationships:
                    models:
                      data: []
                    category:
                      data:
                        id: '11'
                        type: categories
                - id: '6'
                  type: indicators
                  attributes:
                    name: molestiae
                    slug: Category-3
                    version: molestiae
                    position: 25
                    column_name: molestiae
                    operation: molestiae
                  relationships:
                    models:
                      data: []
                    category:
                      data:
                        id: '12'
                        type: categories
                included:
                - id: '10'
                  type: categories
                  attributes:
                    name: voluptatem
                    slug: Category-1
                    description: Enim repellat pariatur. Earum modi eos. Libero tempora
                      exercitationem.
                  relationships:
                    indicators:
                      data:
                      - id: '4'
                        type: indicators
                - id: '11'
                  type: categories
                  attributes:
                    name: cum
                    slug: Category-2
                    description: Placeat commodi libero. Quo recusandae repellat.
                      Sunt commodi tempore.
                  relationships:
                    indicators:
                      data:
                      - id: '5'
                        type: indicators
                - id: '12'
                  type: categories
                  attributes:
                    name: molestiae
                    slug: Category-3
                    description: Et quaerat omnis. Harum voluptas atque. Quo nesciunt
                      voluptas.
                  relationships:
                    indicators:
                      data:
                      - id: '6'
                        type: indicators
                meta:
                  total_indicators: 3
  "/api/journeys":
    get:
      summary: Get list of journeys
      tags:
      - Journey
      parameters:
      - name: locale
        in: query
        description: 'Used language. Default: en'
        required: false
        schema:
          type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                data:
                - id: '324'
                  type: journeys
                  attributes:
                    title: Enim repellat pariatur est.
                    subtitle: Enim repellat pariatur est.
                    theme: Enim repellat pariatur est.
                    background_image:
                      small: http://localhost:3000/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbThFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3745b1fded8936d37214a89223d325c4290b185a/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpRERJd01IZ3lNREFHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--7be8b6f6018bc25ae287d258d8836839fa7642f1/picture.jpg
                      medium: http://localhost:3000/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbThFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3745b1fded8936d37214a89223d325c4290b185a/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpRERnd01IZzRNREFHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--697714719ccce7b35c5f9a02aeef5bd517f3d81f/picture.jpg
                      original: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbThFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3745b1fded8936d37214a89223d325c4290b185a/picture.jpg
                    credits: Enim repellat pariatur est.
                    credits_url: http://kutch-spencer.com/moises
                    published: true
                  relationships:
                    journey_steps:
                      data:
                      - id: '727'
                        type: journey_steps
                      - id: '728'
                        type: journey_steps
                - id: '325'
                  type: journeys
                  attributes:
                    title: Placeat commodi libero et.
                    subtitle: Placeat commodi libero et.
                    theme: Placeat commodi libero et.
                    background_image:
                      small: http://localhost:3000/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbklFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--05460de1db8a52e4d4e34598a368b14b6c3dc0d6/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpRERJd01IZ3lNREFHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--7be8b6f6018bc25ae287d258d8836839fa7642f1/picture.jpg
                      medium: http://localhost:3000/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbklFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--05460de1db8a52e4d4e34598a368b14b6c3dc0d6/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpRERnd01IZzRNREFHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--697714719ccce7b35c5f9a02aeef5bd517f3d81f/picture.jpg
                      original: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbklFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--05460de1db8a52e4d4e34598a368b14b6c3dc0d6/picture.jpg
                    credits: Placeat commodi libero et.
                    credits_url: http://bartoletti.com/jeremiah_cronin
                    published: true
                  relationships:
                    journey_steps:
                      data:
                      - id: '729'
                        type: journey_steps
                      - id: '730'
                        type: journey_steps
                - id: '326'
                  type: journeys
                  attributes:
                    title: Et quaerat omnis veniam.
                    subtitle: Et quaerat omnis veniam.
                    theme: Et quaerat omnis veniam.
                    background_image:
                      small: http://localhost:3000/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBblVFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b75289ce42c963b7ed2e51834c12979c16132241/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpRERJd01IZ3lNREFHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--7be8b6f6018bc25ae287d258d8836839fa7642f1/picture.jpg
                      medium: http://localhost:3000/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBblVFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b75289ce42c963b7ed2e51834c12979c16132241/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpRERnd01IZzRNREFHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--697714719ccce7b35c5f9a02aeef5bd517f3d81f/picture.jpg
                      original: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBblVFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b75289ce42c963b7ed2e51834c12979c16132241/picture.jpg
                    credits: Et quaerat omnis veniam.
                    credits_url: http://hane.com/jules
                    published: true
                  relationships:
                    journey_steps:
                      data:
                      - id: '731'
                        type: journey_steps
                      - id: '732'
                        type: journey_steps
                meta:
                  total: 3
  "/api/journeys/{id}":
    get:
      summary: Get appropriate journey
      tags:
      - Journey
      parameters:
      - name: id
        in: path
        description: Journey ID
        required: true
        schema:
          type: integer
      - name: locale
        in: query
        description: 'Used language. Default: en'
        required: false
        schema:
          type: string
      responses:
        '404':
          description: Not Found
          content:
            application/json:
              example:
                errors:
                - status: '404'
                  title: Record not found
              schema:
                "$ref": "#/components/schemas/errors"
        '200':
          description: success
          content:
            application/json:
              example:
                data:
                  id: '345'
                  type: journeys
                  attributes:
                    title: Autem et et ex.
                    subtitle: Autem et et ex.
                    theme: Autem et et ex.
                    background_image:
                      small: http://localhost:3000/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclFFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c5880e20c33898e9db9f22800829709f90e30bb1/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpRERJd01IZ3lNREFHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--7be8b6f6018bc25ae287d258d8836839fa7642f1/picture.jpg
                      medium: http://localhost:3000/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclFFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c5880e20c33898e9db9f22800829709f90e30bb1/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpRERnd01IZzRNREFHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--697714719ccce7b35c5f9a02aeef5bd517f3d81f/picture.jpg
                      original: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclFFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c5880e20c33898e9db9f22800829709f90e30bb1/picture.jpg
                    credits: Autem et et ex.
                    credits_url: http://jacobson.biz/everett
                    published: true
                  relationships:
                    journey_steps:
                      data:
                      - id: '767'
                        type: journey_steps
                      - id: '770'
                        type: journey_steps
                      - id: '773'
                        type: journey_steps
                      - id: '776'
                        type: journey_steps
                included:
                - id: '767'
                  type: journey_steps
                  attributes:
                    step_type: landing
                    position: 25
                    title: Et quaerat omnis veniam.
                    description: Et quaerat omnis veniam.
                    credits: Et quaerat omnis veniam.
                    credits_url: http://hane.com/jules
                    background_image:
                      small: http://localhost:3000/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWNFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3cd33b794d277bb028e99995be8985c734744a01/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpRERJd01IZ3lNREFHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--7be8b6f6018bc25ae287d258d8836839fa7642f1/picture.jpg
                      medium: http://localhost:3000/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWNFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3cd33b794d277bb028e99995be8985c734744a01/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpRERnd01IZzRNREFHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--697714719ccce7b35c5f9a02aeef5bd517f3d81f/picture.jpg
                      original: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWNFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3cd33b794d277bb028e99995be8985c734744a01/picture.jpg
                - id: '770'
                  type: journey_steps
                  attributes:
                    step_type: conclusion
                    position: 11
                    title: Porro soluta beatae sint.
                    subtitle: Porro soluta beatae sint.
                    content: Porro soluta beatae. Quia ratione facilis. Eligendi sapiente
                      voluptatem.
                    credits: Porro soluta beatae sint.
                    credits_url: http://keebler.info/daine
                    background_color: "#c2e0e0"
                    background_image:
                      small: http://localhost:3000/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXNFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7246cad1f51f8466aaaf6e26d0b831cac76981a3/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpRERJd01IZ3lNREFHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--7be8b6f6018bc25ae287d258d8836839fa7642f1/picture.jpg
                      medium: http://localhost:3000/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXNFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7246cad1f51f8466aaaf6e26d0b831cac76981a3/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpRERnd01IZzRNREFHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--697714719ccce7b35c5f9a02aeef5bd517f3d81f/picture.jpg
                      original: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXNFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7246cad1f51f8466aaaf6e26d0b831cac76981a3/picture.jpg
                - id: '773'
                  type: journey_steps
                  attributes:
                    step_type: chapter
                    position: 93
                    title: Impedit animi eveniet numquam.
                    description: Impedit animi eveniet numquam.
                    chapter_number: 93
                    credits: Impedit animi eveniet numquam.
                    credits_url: http://ritchie.com/jame
                    background_image:
                      small: http://localhost:3000/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcThFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f42db599d532ff40ee6364af02010c8609a61b1b/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpRERJd01IZ3lNREFHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--7be8b6f6018bc25ae287d258d8836839fa7642f1/picture.jpg
                      medium: http://localhost:3000/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcThFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f42db599d532ff40ee6364af02010c8609a61b1b/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpRERnd01IZzRNREFHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--697714719ccce7b35c5f9a02aeef5bd517f3d81f/picture.jpg
                      original: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcThFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f42db599d532ff40ee6364af02010c8609a61b1b/picture.jpg
                - id: '776'
                  type: journey_steps
                  attributes:
                    step_type: embed
                    position: 76
                    content: Eum consequuntur adipisci. Facere iure beatae. In odio
                      reiciendis.
                    source: Eum consequuntur adipisci non.
                    mask_sql: Eum consequuntur adipisci non.
                    map_url: http://lind.name/alana
                    embedded_map_url: http://lind.name/alana
  "/api/layer-groups":
    get:
      summary: Get list of layer groups
      tags:
      - LayerGroup
      parameters:
      - name: site_scope
        in: query
        description: Site scope to list layers for
        required: false
        schema:
          type: string
      - name: locale
        in: query
        description: 'Used language. Default: en'
        required: false
        schema:
          type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                data:
                - id: '5'
                  type: layer_groups
                  attributes:
                    name: voluptatem
                    slug: LayerGroup-1
                    category: voluptatem
                    active: true
                    order: 38
                    info: Enim repellat pariatur. Earum modi eos. Libero tempora exercitationem.
                    layer_group_type: voluptatem
                    super_group_id:
                    super_group_name:
                    icon_class: voluptatem
                  relationships:
                    super_group:
                      data:
                - id: '6'
                  type: layer_groups
                  attributes:
                    name: cum
                    slug: LayerGroup-2
                    category: cum
                    active: true
                    order: 41
                    info: Placeat commodi libero. Quo recusandae repellat. Sunt commodi
                      tempore.
                    layer_group_type: cum
                    super_group_id:
                    super_group_name:
                    icon_class: cum
                  relationships:
                    super_group:
                      data:
                - id: '7'
                  type: layer_groups
                  attributes:
                    name: molestiae
                    slug: LayerGroup-3
                    category: molestiae
                    active: false
                    order: 25
                    info: Et quaerat omnis. Harum voluptas atque. Quo nesciunt voluptas.
                    layer_group_type: molestiae
                    super_group_id:
                    super_group_name:
                    icon_class: molestiae
                  relationships:
                    super_group:
                      data:
                meta:
                  total_layer_groups: 3
  "/api/layers":
    get:
      summary: Get list of layers
      tags:
      - Layer
      parameters:
      - name: site_scope
        in: query
        description: Site scope to list layers for
        required: false
        schema:
          type: string
      - name: locale
        in: query
        description: 'Used language. Default: en'
        required: false
        schema:
          type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                data:
                - id: '27'
                  type: layers
                  attributes:
                    name: voluptatem
                    slug: Layer-1
                    layer_type: voluptatem
                    zindex: 38
                    opacity:
                    active: true
                    order: 38
                    dashboard_order:
                    color: "#ffdbdb"
                    info: voluptatem
                    interactivity: voluptatem
                    css:
                    query:
                    layer_config:
                    layer_provider:
                    published: true
                    locate_layer: false
                    icon_class:
                    legend:
                    zoom_max: 100
                    zoom_min: 0
                    download: false
                    dataset_shortname:
                    dataset_source_url:
                    analysis_suitable: false
                    analysis_query:
                    analysis_body:
                    interaction_config:
                  relationships:
                    layer_group:
                      data:
                        id: '14'
                        type: layer_groups
                    sources:
                      data: []
                    agrupation:
                      data:
                        id: 4
                        layer_id: 27
                        layer_group_id: 14
                        active: false
                - id: '28'
                  type: layers
                  attributes:
                    name: cum
                    slug: Layer-2
                    layer_type: cum
                    zindex: 41
                    opacity:
                    active: true
                    order: 41
                    dashboard_order:
                    color: "#eaf1ea"
                    info: cum
                    interactivity: cum
                    css:
                    query:
                    layer_config:
                    layer_provider:
                    published: true
                    locate_layer: false
                    icon_class:
                    legend:
                    zoom_max: 100
                    zoom_min: 0
                    download: false
                    dataset_shortname:
                    dataset_source_url:
                    analysis_suitable: false
                    analysis_query:
                    analysis_body:
                    interaction_config:
                  relationships:
                    layer_group:
                      data:
                        id: '14'
                        type: layer_groups
                    sources:
                      data: []
                    agrupation:
                      data:
                        id: 5
                        layer_id: 28
                        layer_group_id: 14
                        active: false
                - id: '29'
                  type: layers
                  attributes:
                    name: molestiae
                    slug: Layer-3
                    layer_type: molestiae
                    zindex: 25
                    opacity:
                    active: false
                    order: 25
                    dashboard_order:
                    color: "#157e15"
                    info: molestiae
                    interactivity: molestiae
                    css:
                    query:
                    layer_config:
                    layer_provider:
                    published: true
                    locate_layer: false
                    icon_class:
                    legend:
                    zoom_max: 100
                    zoom_min: 0
                    download: false
                    dataset_shortname:
                    dataset_source_url:
                    analysis_suitable: false
                    analysis_query:
                    analysis_body:
                    interaction_config:
                  relationships:
                    layer_group:
                      data:
                        id: '14'
                        type: layer_groups
                    sources:
                      data: []
                    agrupation:
                      data:
                        id: 6
                        layer_id: 29
                        layer_group_id: 14
                        active: false
                meta:
                  total_layers: 3
  "/api/layers/{id}/downloads":
    get:
      summary: Download layer file
      tags:
      - Layer
      parameters:
      - name: id
        in: path
        description: Layer ID
        required: true
        schema:
          type: integer
      - name: download_path
        in: query
        description: Url to the file download
        required: false
        schema:
          type: string
      - name: file_format
        in: query
        description: File format (pdf, kml, jpg, txt, etc..)
        required: false
        schema:
          type: string
      - name: with_format
        in: query
        description: If format is part of download_path
        required: false
        schema:
          type: string
      responses:
        '200':
          description: success
  "/api/menu-entries":
    get:
      summary: Get list of map menu entries
      tags:
      - MapMenuEntry
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                data:
                - id: '4'
                  type: map_menu_entries
                  attributes:
                    label: Otha Kemmer
                    link: http://kutch-spencer.com/moises
                    position: 38
                    ancestry:
                - id: '5'
                  type: map_menu_entries
                  attributes:
                    label: Msgr. Genaro Cronin
                    link: http://bartoletti.com/jeremiah_cronin
                    position: 41
                    ancestry:
                - id: '6'
                  type: map_menu_entries
                  attributes:
                    label: Raymon Wisoky
                    link: http://hane.com/jules
                    position: 25
                    ancestry:
  "/api/models":
    get:
      summary: Get list of models
      tags:
      - Model
      parameters:
      - name: site_scope
        in: query
        description: Site scope to list layers for
        required: false
        schema:
          type: integer
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                data:
                - id: '5'
                  type: models
                  attributes:
                    name: voluptatem
                    description: Enim repellat pariatur. Earum modi eos. Libero tempora
                      exercitationem.
                    source: Enim repellat pariatur est.
                    query_analysis: Enim repellat pariatur est.
                    table_name: voluptatem
                  relationships:
                    site_scopes:
                      data:
                      - id: '1'
                        type: site_scopes
                    indicators:
                      data: []
                - id: '6'
                  type: models
                  attributes:
                    name: cum
                    description: Placeat commodi libero. Quo recusandae repellat.
                      Sunt commodi tempore.
                    source: Placeat commodi libero et.
                    query_analysis: Placeat commodi libero et.
                    table_name: cum
                  relationships:
                    site_scopes:
                      data:
                      - id: '1'
                        type: site_scopes
                    indicators:
                      data: []
                - id: '7'
                  type: models
                  attributes:
                    name: molestiae
                    description: Et quaerat omnis. Harum voluptas atque. Quo nesciunt
                      voluptas.
                    source: Et quaerat omnis veniam.
                    query_analysis: Et quaerat omnis veniam.
                    table_name: molestiae
                  relationships:
                    site_scopes:
                      data:
                      - id: '1'
                        type: site_scopes
                    indicators:
                      data: []
                - id: '8'
                  type: models
                  attributes:
                    name: quos
                    description: Dolores fugiat nesciunt. Ut laborum dolores. Sit
                      neque eos.
                    source: Dolores fugiat nesciunt accusantium.
                    query_analysis: Dolores fugiat nesciunt accusantium.
                    table_name: quos
                  relationships:
                    site_scopes:
                      data:
                      - id: '2'
                        type: site_scopes
                    indicators:
                      data: []
                included:
                - id: '1'
                  type: site_scopes
                  attributes:
                    name: CIGRP
                    color: "#ffdbdb"
                    subdomain: voluptatem
                    has_analysis: true
                    latitude: -14.936039153536683
                    longitude: -29.872078307073366
                    header_theme: Enim repellat pariatur est.
                    zoom_level: 38
                    linkback_text: Enim repellat pariatur. Earum modi eos. Libero
                      tempora exercitationem.
                    linkback_url: http://kutch-spencer.com/moises
                    header_color: "#ffdbdb"
                    logo_url: http://kutch-spencer.com/moises
                    predictive_model: true
                    analysis_options: true
                    analytics_code:
                    has_gef_logo:
                  relationships:
                    site_pages:
                      data: []
                - id: '2'
                  type: site_scopes
                  attributes:
                    name: Otha Kemmer
                    color: "#eaf1ea"
                    subdomain: cum
                    has_analysis: true
                    latitude: -11.520917614439327
                    longitude: -23.041835228878654
                    header_theme: Placeat commodi libero et.
                    zoom_level: 41
                    linkback_text: Placeat commodi libero. Quo recusandae repellat.
                      Sunt commodi tempore.
                    linkback_url: http://bartoletti.com/jeremiah_cronin
                    header_color: "#eaf1ea"
                    logo_url: http://bartoletti.com/jeremiah_cronin
                    predictive_model: true
                    analysis_options: true
                    analytics_code:
                    has_gef_logo:
                  relationships:
                    site_pages:
                      data: []
                meta:
                  total_models: 4
  "/services/oembed":
    get:
      summary: Get appropriate iframe
      tags:
      - Oembed
      parameters:
      - name: url
        in: query
        required: false
        schema:
          type: string
      - name: format
        in: query
        required: false
        schema:
          type: string
      - name: maxwidth
        in: query
        required: false
        schema:
          type: integer
      - name: maxheight
        in: query
        required: false
        schema:
          type: integer
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                width: 960
                height: 600
                version: '1.0'
                type: rich
                provider_name: resilienceatlas.org
                provider_url: http://resilienceatlas.org
                html: <iframe frameborder="0" width="960" height="600" src="https://resilienceatlas.org/embed/map?test=test"></iframe>
        '400':
          description: Domain does not include map path
        '403':
          description: Domain is not permitted
        '404':
          description: Domain information is missing
        '422':
          description: Domain is not url or base64 string
  "/api/photos":
    post:
      summary: Save new image
      tags:
      - Photo
      parameters: []
      responses:
        '201':
          description: success
          content:
            application/json:
              example:
                id: 2
                image_data: '{"id":"5e44c00559f4aae9bbba3829d53b3616.jpg","storage":"store","metadata":{"filename":"picture.jpg","size":32326,"mime_type":null}}'
                created_at: '2023-03-15T13:04:23.406+01:00'
                updated_at: '2023-03-15T13:04:23.412+01:00'
                url: "/uploads/store/5e44c00559f4aae9bbba3829d53b3616.jpg"
                image_url: "/uploads/store/5e44c00559f4aae9bbba3829d53b3616.jpg"
  "/users/register":
    post:
      summary: Register new user
      tags:
      - User
      parameters: []
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                status: created
        '422':
          description: Validation errors
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
                      nullable: true
                    first_name:
                      type: string
                      nullable: true
                    last_name:
                      type: string
                      nullable: true
                    organization:
                      type: string
                      nullable: true
                    organization_role:
                      type: string
                      nullable: true
                  required:
                  - email
                  - password
                required:
                - user
  "/api/share/{uid}":
    get:
      summary: Get detail of shared url
      tags:
      - ShareUrl
      parameters:
      - name: uid
        in: path
        description: An unique url identifier
        required: true
        schema:
          type: string
      responses:
        '404':
          description: Not Found
          content:
            application/json:
              example:
                errors:
                - status: '404'
                  title: Record not found
              schema:
                "$ref": "#/components/schemas/errors"
        '200':
          description: success
          content:
            application/json:
              example:
                data:
                  id: '2'
                  type: share_urls
                  attributes:
                    uid: '12345'
                    body: body test
  "/api/share":
    post:
      summary: Create new shared url
      tags:
      - ShareUrl
      parameters:
      - name: body
        in: query
        description: Body of shared url
        schema:
          type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                uid: f3f1245d0c9bf08b4cb8
  "/api/sites":
    get:
      summary: Get list of all site scopes
      tags:
      - SiteScope
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                data:
                - id: '1'
                  type: site_scopes
                  attributes:
                    name: CIGRP
                    color: "#ffdbdb"
                    subdomain: voluptatem
                    has_analysis: true
                    latitude: -14.936039153536683
                    longitude: -29.872078307073366
                    header_theme: Enim repellat pariatur est.
                    zoom_level: 38
                    linkback_text: Enim repellat pariatur. Earum modi eos. Libero
                      tempora exercitationem.
                    linkback_url: http://kutch-spencer.com/moises
                    header_color: "#ffdbdb"
                    logo_url: http://kutch-spencer.com/moises
                    predictive_model: true
                    analysis_options: true
                    analytics_code:
                    has_gef_logo:
                  relationships:
                    site_pages:
                      data: []
                - id: '2'
                  type: site_scopes
                  attributes:
                    name: Otha Kemmer
                    color: "#eaf1ea"
                    subdomain: cum
                    has_analysis: true
                    latitude: -11.520917614439327
                    longitude: -23.041835228878654
                    header_theme: Placeat commodi libero et.
                    zoom_level: 41
                    linkback_text: Placeat commodi libero. Quo recusandae repellat.
                      Sunt commodi tempore.
                    linkback_url: http://bartoletti.com/jeremiah_cronin
                    header_color: "#eaf1ea"
                    logo_url: http://bartoletti.com/jeremiah_cronin
                    predictive_model: true
                    analysis_options: true
                    analytics_code:
                    has_gef_logo:
                  relationships:
                    site_pages:
                      data: []
  "/api/site":
    get:
      summary: Get appropriate site scope
      tags:
      - SiteScope
      parameters:
      - name: site_scope
        in: query
        description: Site scope subdomain
        required: false
        schema:
          type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                data:
                  id: '1'
                  type: site_scopes
                  attributes:
                    name: CIGRP
                    color: "#ffdbdb"
                    subdomain: voluptatem
                    has_analysis: true
                    latitude: -14.936039153536683
                    longitude: -29.872078307073366
                    header_theme: Enim repellat pariatur est.
                    zoom_level: 38
                    linkback_text: Enim repellat pariatur. Earum modi eos. Libero
                      tempora exercitationem.
                    linkback_url: http://kutch-spencer.com/moises
                    header_color: "#ffdbdb"
                    logo_url: http://kutch-spencer.com/moises
                    predictive_model: true
                    analysis_options: true
                    analytics_code:
                    has_gef_logo:
                  relationships:
                    site_pages:
                      data: []
  "/users/me":
    get:
      summary: Obtains information about current user
      tags:
      - User
      security:
      - bearerAuth: []
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                errors:
                - status: '401'
                  title: Unauthorized
        '200':
          description: success
          content:
            application/json:
              example:
                id: 7
                email: person-1@example.com
                created_at: '2023-03-15T13:04:23.732+01:00'
                updated_at: '2023-03-15T13:04:23.732+01:00'
                first_name: Dawna
                last_name: Block
                phone: "(995) 001-7692 x452"
                organization: voluptatem
                organization_role: voluptatem
    patch:
      summary: Update current user
      tags:
      - User
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                errors:
                - status: '401'
                  title: Unauthorized
        '200':
          description: success
          content:
            application/json:
              example:
                first_name: Jan
                last_name: Kowalski
                email: jankowalski@example.com
                id: 9
                created_at: '2023-03-15T13:04:23.782+01:00'
                updated_at: '2023-03-15T13:04:23.797+01:00'
                phone: "(995) 001-7692 x452"
                organization: voluptatem
                organization_role: voluptatem
        '422':
          description: Validation errors
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
                      nullable: true
                    first_name:
                      type: string
                      nullable: true
                    last_name:
                      type: string
                      nullable: true
                    organization:
                      type: string
                      nullable: true
                    organization_role:
                      type: string
                      nullable: true
                  required:
                  - email
                  - password
                required:
                - user
components:
  securitySchemes:
    tokenAuth:
      type: http
      scheme: bearer
      name: Authorization
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      name: Authorization
  schemas:
    errors:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              status:
                type: string
              title:
                type: string
            required:
            - status
            - title
      required:
      - errors
servers:
- url: ''
- url: "{scheme}://{host}"
  variables:
    scheme:
      default: http
    host:
      default: localhost:3000
